const EL_MC			= Cint(0)
const EL_MD			= Cint(1)
const EL_MR			= Cint(2)
const EL_VC			= Cint(3)
const EL_VR			= Cint(4)
const EL_STAR		= Cint(5)
const EL_CIRC		= Cint(6)

const EL_NORMAL 	= Cint(0)
const EL_TRANSPOSE 	= Cint(1)
const EL_ADJOINT 	= Cint(2)
