name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - x64
        exclude:
          - os: macos-latest
            arch: x64
        include:
          - os: macos-latest
            arch: aarch64
            version: '1'
          - os: ubuntu-latest
            arch: x64
            version: 'pre'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
